# Generated by Django 3.1.2 on 2020-11-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
